### ISSUE TITLE
Is the algorithm suitable for unorganized point cloud?

### ISSUE THREAD

**Issue by JR9124** [acschaefer/ppe#1]
I read that `PC is a pointCloud object that represents an organized point cloud.` in pcextrpln.m, so I'm wondering whether the algorithm is suitable for unorganized point cloud or not.

**Comment by acschaefer** [comment]
PPE can only work on organized point clouds. For more details, please see the [paper](http://ais.informatik.uni-freiburg.de/publications/papers/schaefer19icra.pdf).
